import { Metadata } from "next";
import "@4k/ui/styles/globals.css";
import { Nunito } from 'next/font/google';
const nunito = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${nunito.className} antialiased`} suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}
