import { Metadata } from "next";
import "./globals.css";
import { Nunito } from 'next/font/google';
const nunito = Nunito({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "4Kadventures",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${nunito.className} antialiased`} suppressHydrationWarning>
        <div className="min-h-screen bg-background overflow-hidden md:overflow-visible relative">
          {children}
        </div>
      </body>
    </html>
  );
}
