import { Metadata } from "next";
import "@4k/ui/styles/globals.css";
import "./globals.css";
import { Montserrat } from 'next/font/google';
import { Providers } from "./provider";
import Header from "@/src/components/headers";
import Footer from "@/src/components/footers";
const nunito = Montserrat({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: "4K Adventures",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}>) {
  const { locale } = await params;
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${nunito.className} antialiased relative`} suppressHydrationWarning>
        <Providers locale={locale}>
          <Header />
          <div className="min-h-screen bg-background overflow-hidden md:overflow-visible relative">
            {children}
          </div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
